export const footerCategories = [
  'Ordinateurs',
  'Smartphones',
  'Tablettes',
  'Télévisions',
  'Casques audio',
  'Écouteurs',
  'Haut-parleurs & barres de son',
  'Appareils photo',
  'Drones',
  'Montres connectées',
  'Souris',
  'Claviers',
  'Câbles & chargeurs',
  'Clés USB & stockage',
  'Imprimantes',
  'Électroménager',
  'Cuisine',
  'Vélos',
  'Paillassons & tapis d’entrée',
  'Gadgets & accessoires',
];

export const footerQuickLinks = [
  { label: 'Catalogue', href: '/all-products' },
  { label: 'Offres étudiantes', href: '/offer' },
  { label: 'Contact', href: '/contact' },
  { label: 'Politique de confidentialité', href: '/privacy-policy' },
  { label: 'Cookies', href: '/cookies' },
];
